-- Update Communication model for candidate-centric approach
-- This migration:
--   1) Adds candidateId column (required) - who you're communicating with
--   2) Backfills candidateId from JobApplication.candidateId
--   3) Makes applicationId optional (nullable) - job context is optional
--   4) Adds isAutoGenerated flag to track automated vs manual communications
--   5) Adds indexes for performance
--   6) Adds foreign key constraint for candidateId

-- Step 1: Add candidateId column (nullable initially for backfill)
ALTER TABLE "Communication" ADD COLUMN "candidateId" TEXT;

-- Step 2: Backfill candidateId from JobApplication
-- Every communication has an applicationId, so we can get candidateId from it
UPDATE "Communication" c
SET "candidateId" = ja."candidateId"
FROM "JobApplication" ja
WHERE c."applicationId" = ja.id
  AND c."candidateId" IS NULL;

-- Step 3: Make candidateId NOT NULL (safe after backfill)
-- Check if all communications have candidateId before making it required
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM "Communication"
    WHERE "candidateId" IS NULL
  ) THEN
    RAISE EXCEPTION 'Cannot make candidateId NOT NULL: some communications have NULL candidateId';
  END IF;

  ALTER TABLE "Communication" ALTER COLUMN "candidateId" SET NOT NULL;
END $$;

-- Step 4: Add foreign key constraint for candidateId
ALTER TABLE "Communication"
ADD CONSTRAINT "Communication_candidateId_fkey"
FOREIGN KEY ("candidateId") REFERENCES "Candidate"(id) ON DELETE CASCADE;

-- Step 5: Make applicationId optional (nullable)
ALTER TABLE "Communication" ALTER COLUMN "applicationId" DROP NOT NULL;

-- Step 6: Update foreign key constraint for applicationId to allow NULL
-- Drop existing constraint if it exists
ALTER TABLE "Communication"
DROP CONSTRAINT IF EXISTS "Communication_applicationId_fkey";

-- Recreate with ON DELETE SET NULL to handle nullable relationship
ALTER TABLE "Communication"
ADD CONSTRAINT "Communication_applicationId_fkey"
FOREIGN KEY ("applicationId") REFERENCES "JobApplication"(id) ON DELETE SET NULL;

-- Step 7: Add isAutoGenerated column (default false)
ALTER TABLE "Communication" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- Step 8: Add indexes for performance
CREATE INDEX IF NOT EXISTS "Communication_candidateId_idx" ON "Communication"("candidateId");
CREATE INDEX IF NOT EXISTS "Communication_type_idx" ON "Communication"("type");
CREATE INDEX IF NOT EXISTS "Communication_sentAt_idx" ON "Communication"("sentAt");

-- Note: applicationId, interviewId, and sentById indexes already exist from previous migration

